### ISSUE TITLE
compiling with tic segfaults on macos

### ISSUE THREAD

**Issue by aaronjensen** [dieggsy/eterm-256color#1]
macOS doesn't appear to like it when you attempt to install a ti with tic that uses a terminfo it doesn't know about. I don't have an `eterm-color` installed (should I?). If I change `use=eterm-color` to `use=xterm-color` it works fine.

Thanks for this package btw, I've wanted something like this for a while! Now what would it take to get 24-bit support... 😄

**Comment by aaronjensen** [comment]
One other thing, on macOS when it is installed, it gets installed to `~/.terminfo/65/eterm-256color` so your exists check doesn't work.

**Comment by dieggsy** [comment]
Hmm, I suspected the install location might not always be the same. 

Could you tell me a little more about your emacs setup? Version, how you installed? In particular, what was the default value of `term-term-name` (without this package)?

**Comment by aaronjensen** [comment]
Emacs 26.0.90, built from the emacs-26 branch about a week ago.

`term-term-name` is `eterm-color`.

**Comment by dieggsy** [comment]
@aaronjensen huh. if `term-term-name` is `eterm-color`, and `ansi-term` worked without this pacakage, I would sorta expect you to have `eterm-color` somewhere. How did you verify it doesn't exist? I think emacs should install `eterm-color`, especially if you're building youself, though I haven't used macOS in a while so there may be some funkiness I don't know about.

**Comment by aaronjensen** [comment]
It doesn't install it itself, I just discovered that I need to install it manually. I have done so and now I can install your original ti. That may be worth referencing in the readme

**Comment by dieggsy** [comment]
@aaronjensen since I can't test this myself, could describe how you installed it manually (and PR if you wish)?

**Comment by dieggsy** [comment]
Could probably add this under the Notes section

**Comment by dieggsy** [comment]
Regarding 24-bit support, I do have some ideas...

**Comment by aaronjensen** [comment]
> Regarding 24-bit support, I do have some ideas...

Awesome!

**Comment by aaronjensen** [comment]
btw, you could possibly check to see if `eterm-color` is installed before attempting to install `eterm-256color`. That may alleviate some confusion.

**Comment by dieggsy** [comment]
That's probably a good idea.

**Comment by dieggsy** [comment]
@aaronjensen Please test. Note that now the term type check has been pulled into a function on its own that should be terminfo compliant (that is, follow the guidelines in the `tic` manpage) and therefore hopefully exhaustive.

Additionally, the package also checks for the existence `eterm-color`, and if it doesn't exist optionally offers to fetch it from https://github.com/emacs-mirror/emacs and compile it as well.

**Comment by aaronjensen** [comment]
I cleared out my terminfo and gave it a shot. It worked perfectly. Thanks for the fix.

**Comment by dieggsy** [comment]
@aaronjensen to clarify, did it also fetch and compile `eterm-color` ?

**Comment by aaronjensen** [comment]
Yes, it did.
