### ISSUE TITLE
error in process filter: Symbol’s value as variable is void: term-terminal-previous-parameter

### ISSUE THREAD

**Issue by wedens** [dieggsy/eterm-256color#12]
After `eterm-256color-mode` in `ansi-term`, I get `error in process filter: Symbol’s value as variable is void: term-terminal-previous-parameter`.

backtrace:
```
Debugger entered--Lisp error: (void-variable term-terminal-previous-parameter)
  eterm-256color-handle-colors(0)
  apply(eterm-256color-handle-colors 0)
  term-handle-colors-array(0)
  mapc(term-handle-colors-array (0))
  term-handle-ansi-escape(#<process *ansi-term*> (0) 109)
  term-emulate-terminal(#<process *ansi-term*> "\15\33[m\33[27m\33[24m\33[J\33[36m~ \33[32m\342\235\257\33[39m\33[49m \33[K\15\15\33[...")
```
Emacs: 27.0.50
eterm-256color: 1340f69 (latest master)

**Comment by dieggsy** [comment]
Does the devel branch work for you? term.el was somewhat changed in emacs 26-ish

**Comment by wedens** [comment]
yeah, looks like develop works. any reason it's not merged in master?

**Comment by dieggsy** [comment]
@wedens yeah, the reason it's not merged is there's a bug I've been a bit too distracted to fix with emacs 25 on that branch, so it's not backward compatible and emacs 27 (where term.el was actually changed, my last comment was inaccurate) isn't yet the stable version.

I've been putting off fixing it for... way too long now. I'll try to give it a solid look tomorrow.

**Comment by dieggsy** [comment]
@wedens I should have fixed the issue with emacs 25 now, and the devel code is merged in master. (note it's not in melpa stable yet, as I've not tagged it pending responses from the original bug reporters). Closing this for now, will reopen if necessary.
