### ISSUE TITLE
`tic: Too many file names.` on macOS 10.15

### ISSUE THREAD

**Issue by aGolduck** [dieggsy/eterm-256color#15]
should be `tic /Applications/Emacs.app/Contents/Resources/etc/e/eterm-color.ti` without `~/.terminfo`

**Comment by dieggsy** [comment]
Could you explain the issue more clearly? I don't fully understand what you're saying. The package should download `eterm-color.ti` to `/tmp/` when it doesn't find it in default dirs (including `~/.terminfo` and `/usr/share/terminfo`) and compile using `tic -s /tmp/eterm-color.ti`.

**Comment by aGolduck** [comment]
Sorry, I was saying how to install eterm-color manually on macOS.
```
% tic ~/.terminfo /Applications/Emacs.app/Contents/Resources/etc/e/eterm-color.ti
tic: Too many file names.  Usage:
	tic [-e names] [-o dir] [-R name] [-v[n]] [-V] [-w[n]] [-1aCcfGgILNrsTtUx] source-file
```

**Comment by dieggsy** [comment]
@aGolduck ah, ok. It's been a long while since I've been on macOS. Could you check if it works with `tic -o ~/.terminfo /Applications/Emacs.app/Contents/Resources/etc/e/eterm-color.ti` instead ?

**Comment by aGolduck** [comment]
yes, it works. @dieggsy

**Comment by dieggsy** [comment]
I've updated the README
