### ISSUE TITLE
tic : too many filenames

### ISSUE THREAD

**Issue by azzamsa** [dieggsy/eterm-256color#8]
I get the error message running `tic` in my terminal

```
$ tic $(find /usr/share/emacs -name 'eterm-color.ti')
tic: Too many file names.  Usage:
        tic [-e names] [-o dir] [-R name] [-v[n]] [-V] [-w[n]] [-1aCDcfGgIKLNrsTtUx] source-file
```

**Comment by dieggsy** [comment]
Uh, sorry for the late reply, can you tellme the output of just `find /usr/share/emacs -name 'eterm-color.ti'` ?

**Comment by azzamsa** [comment]
``` bash
$ find /usr/share/emacs -name 'eterm-color.ti'
/usr/share/emacs/25.1/etc/e/eterm-color.ti
/usr/share/emacs/24.5/etc/e/eterm-color.ti
```

**Comment by dieggsy** [comment]
Oh, uh weird. just tic the one of the version you're using (though it's probably the same anyway)

**Comment by azzamsa** [comment]
Oh. Okay.

**Comment by azzamsa** [comment]
I just realized that it's just `find /usr/share/emacs` a way to specify emacs config dir. 

The bad thing happened when we have multiple emacs instalation. :)
